server:
  port: 9890
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  mail:
    host: smtp.gmail.com
    port: 465
    username: challadivyasri94@gmail.com
    password: kueyhiircsrrdbke
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




